name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    - name: Validate wrapper and restore Gradle cache
      uses: gradle/actions/setup-gradle@v4
    - name: Build with Gradle
      run: ./gradlew pmdMain build
    - name: PMD report
      uses: jwgmeligmeyling/pmd-github-action@v1
      if: failure()
      with:
        path: '**/reports/pmd/main.xml'
    - name: Stop Gradle
      run: |
        RELEASE_MODE=${{ startsWith(github.ref, 'refs/tags/release-') && '1' || '0' }} \
        ./gradlew --stop
    - name: Calculate artifact names
      id: calculate_artifact_names
      run: |
        # Check is backwards because "" is falsey, which wouldn't work for boolean punning or atleast thats what John Botania says
        SNAPSHOT_SUFFIX=${{ !startsWith(github.ref, 'refs/tags/release-') && '-SNAPSHOT' || '' }}
        VERSION=$(awk -F '=' '/^version/ { print $2; }' build.properties)
        BUILD=$(awk -F '=' '/build_number/ { print $2; }' build.properties)
        echo "forge=build/libs/Quark-${VERSION}-${BUILD}${SNAPSHOT_SUFFIX}.jar" >> "$GITHUB_OUTPUT"
    - name: Sign jars
      env:
        SIGNING_KEY: ${{ secrets.VIOLET_MOON_SIGNING_KEY }}
      if: ${{ env.SIGNING_KEY != '' }}
      run: |
        echo "${SIGNING_KEY}" | gpg --import -
        gpg --local-user "Violet Moon Signing Key" --armor \
          --detach-sign ${{ steps.calculate_artifact_names.outputs.forge }}
    - name: Archive Forge Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Forge
        path: |
          ${{ steps.calculate_artifact_names.outputs.forge }}
          ${{ steps.calculate_artifact_names.outputs.forge }}.asc
    - name: Upload Releases
      if: startsWith(github.ref, 'refs/tags/release-')
      env:
        GH_TOKEN: ${{ github.token }}
        GIT_REF: ${{ github.ref }}
        FORGE_JAR: ${{ steps.calculate_artifact_names.outputs.forge }}
        CURSEFORGE_TOKEN: ${{ secrets.VAZKII_CURSEFORGE_TOKEN }}
        MODRINTH_TOKEN: ${{ secrets.VAZKII_MODRINTH_TOKEN }}
      run: |
        scripts/upload_releases.sh
